In [2]:
from bs4 import BeautifulSoup
import requests
url=BeautifulSoup('https://www.worldometers.info/coronavirus/','html.parser')
start=requests.get(url)
s1=start.text
soup=BeautifulSoup(s1,'lxml')
tags=soup.table

tag=tags.find_all('tr')
list1=[]
for i in range(len(tag)):
    x=tag[i].get_text()
    list1.append(x)
del list1[1:7]
del list1[1:3]
list1=list1[:216]
final=[]
for j in list1:
 y=j.split('\n')
 final.append(y)
final

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>9,262,436</td>
<td>+5,512</td>
<td>320,953</td>
<td>+489</td>
<td>6,044,481</td>
<td>+3,918</td>
<td>2,897,002</td>
<td>17,868</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>11,290,497</td>
<td>+811</td>
<td>204,861</td>
<td>+15</td>
<td>9,590,174</td>
<td>+938</td>
<td>1,495,462</td>
<td>20,687</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>8,396,844</td>
<td>+361</td>
<td>264,204</td>
<td>+27</td>
<td>7,284,171</td>
<td>+535</td>
<td>848,469</td>
<td>18,003</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>5,524,920</td>
<td>+2,088</td>
<td>226,746</td>
<td>+14</td>
<td>2,921,896</td>
<td>+93</td>
<td>2,376,278</td>
<td>9,637</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>1,534,494</td>
<td></td>
<td>36,885</td>
<td></td>
<td>1,275,086</td>
<td></td>
<td>222,523</td>
<td>1,607</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>31,871</td>
<td>+10</td>
<td>940</td>
<td>+2</td>
<td>29,067</td>
<td>+9</td>
<td>1,864</td>
<td>15</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>651</td>
<td></td>
<td>55</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>36,041,783</td>
<td>+8,782</td>
<td>1,054,604</td>
<td>+547</td>
<td>27,145,526</td>
<td>+5,493</td>
<td>7,841,653</td>
<td>67,821</td>
<td>4,624</td>
<td>135.3</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">7,722,746</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">215,822 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">4,935,545</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">2,571,379</td>
<td style="font-weight: bold; text-align:right">14,508</td>
<td style="font-weight: bold; text-align:right">23,295</td>
<td style="font-weight: bold; text-align:right">651</td>
<td style="font-weight: bold; text-align:right">113,319,318</td>
<td style="font-weight: bold; text-align:right">341,816</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">331,521,024</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>43</td><td>1,536</td><td>3</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">6,754,179</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">104,591 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">5,741,253</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">908,335</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">4,882</td>
<td style="font-weight: bold; text-align:right">76</td>
<td style="font-weight: bold; text-align:right">81,071,797</td>
<td style="font-weight: bold; text-align:right">58,595</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,383,604,455</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>205</td><td>13,229</td><td>17</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">4,970,953</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">147,571 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">4,352,871</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">470,511</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">23,342</td>
<td style="font-weight: bold; text-align:right">693</td>
<td style="font-weight: bold; text-align:right">17,900,000</td>
<td style="font-weight: bold; text-align:right">84,053</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">212,962,134</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>43</td><td>1,443</td><td>12</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">1,237,504</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">21,663 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">988,576</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">227,265</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">8,479</td>
<td style="font-weight: bold; text-align:right">148</td>
<td style="font-weight: bold; text-align:right">48,337,992</td>
<td style="font-weight: bold; text-align:right">331,193</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,951,318</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>118</td><td>6,737</td><td>3</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>
<td style="font-weight: bold; text-align:right">869,808</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">27,017 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">770,812</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">71,979</td>
<td style="font-weight: bold; text-align:right">2,220</td>
<td style="font-weight: bold; text-align:right">17,046</td>
<td style="font-weight: bold; text-align:right">529</td>
<td style="font-weight: bold; text-align:right">3,967,885</td>
<td style="font-weight: bold; text-align:right">77,761</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/colombia-population/">51,026,600</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>59</td><td>1,889</td><td>13</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">865,631</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">32,486 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">1,544</td>
<td style="font-weight: bold; text-align:right">18,512</td>
<td style="font-weight: bold; text-align:right">695</td>
<td style="font-weight: bold; text-align:right">13,689,776</td>
<td style="font-weight: bold; text-align:right">292,769</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,759,656</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>54</td><td>1,439</td><td>3</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/peru/">Peru</a></td>
<td style="font-weight: bold; text-align:right">832,929</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">32,914 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">718,065</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">81,950</td>
<td style="font-weight: bold; text-align:right">1,268</td>
<td style="font-weight: bold; text-align:right">25,169</td>
<td style="font-weight: bold; text-align:right">995</td>
<td style="font-weight: bold; text-align:right">3,975,007</td>
<td style="font-weight: bold; text-align:right">120,117</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/peru-population/">33,092,889</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>40</td><td>1,005</td><td>8</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>
<td style="font-weight: bold; text-align:right">824,468</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">21,827 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">660,272</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">142,369</td>
<td style="font-weight: bold; text-align:right">4,007</td>
<td style="font-weight: bold; text-align:right">18,198</td>
<td style="font-weight: bold; text-align:right">482</td>
<td style="font-weight: bold; text-align:right">2,110,994</td>
<td style="font-weight: bold; text-align:right">46,594</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/argentina-population/">45,305,938</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>55</td><td>2,076</td><td>21</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>
<td style="font-weight: bold; text-align:right">794,608</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+4,828</td>
<td style="font-weight: bold; text-align:right;">82,348 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+471</td>
<td style="font-weight: bold; text-align:right">557,478</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,541</td>
<td style="text-align:right;font-weight:bold;">154,782</td>
<td style="font-weight: bold; text-align:right">2,417</td>
<td style="font-weight: bold; text-align:right">6,146</td>
<td style="font-weight: bold; text-align:right">637</td>
<td style="font-weight: bold; text-align:right">2,021,255</td>
<td style="font-weight: bold; text-align:right">15,633</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/mexico-population/">129,291,789</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>163</td><td>1,570</td><td>64</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-africa/">South Africa</a></td>
<td style="font-weight: bold; text-align:right">683,242</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">17,103 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">616,857</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">49,282</td>
<td style="font-weight: bold; text-align:right">539</td>
<td style="font-weight: bold; text-align:right">11,482</td>
<td style="font-weight: bold; text-align:right">287</td>
<td style="font-weight: bold; text-align:right">4,294,931</td>
<td style="font-weight: bold; text-align:right">72,176</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-africa-population/">59,506,184</a> </td>
<td data-continent="Africa" style="display:none">Africa</td>
<td>87</td><td>3,479</td><td>14</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">634,763</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">32,365 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">99,295</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">503,103</td>
<td style="font-weight: bold; text-align:right">1,426</td>
<td style="font-weight: bold; text-align:right">9,719</td>
<td style="font-weight: bold; text-align:right">496</td>
<td style="font-weight: bold; text-align:right">11,699,517</td>
<td style="font-weight: bold; text-align:right">179,132</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,312,309</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>103</td><td>2,018</td><td>6</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">530,113</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">42,445 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">393</td>
<td style="font-weight: bold; text-align:right">7,798</td>
<td style="font-weight: bold; text-align:right">624</td>
<td style="font-weight: bold; text-align:right">26,147,138</td>
<td style="font-weight: bold; text-align:right">384,622</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">67,981,342</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>128</td><td>1,602</td><td>3</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iran/">Iran</a></td>
<td style="font-weight: bold; text-align:right">479,825</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">27,419 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">394,800</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">57,606</td>
<td style="font-weight: bold; text-align:right">4,200</td>
<td style="font-weight: bold; text-align:right">5,693</td>
<td style="font-weight: bold; text-align:right">325</td>
<td style="font-weight: bold; text-align:right">4,179,338</td>
<td style="font-weight: bold; text-align:right">49,591</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/iran-population/">84,276,796</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>176</td><td>3,074</td><td>20</td>
</tr>
<tr style="">

In [6]:
from bs4 import BeautifulSoup
import requests
url=BeautifulSoup('http://www.nepalstock.com/floorsheet','html.parser')
response=requests.get(url)
data=response.text
soup=BeautifulSoup(data,'lxml')
#soup
tag=soup.table
tags=tag.find_all('tr')
#tags
list1=[]
for i in range(len(tags)):
    x=tags[i].get_text()
    list1.append(x)
#list1
list1=list1[1:-3]
list2=[]
for i in list1:
    y=i.split('\n')[1:-1]
    list2.append(y)
list2

[['S.N.',
  'Contract No',
  'Stock Symbol',
  'Buyer Broker',
  'Seller Broker',
  'Quantity',
  'Rate',
  'Amount'],
 ['1', '2020100403012017', 'NRIC', '42', '56', '40', '895', '35800.00'],
 ['2', '2020100403012814', 'GUFL', '38', '5', '85', '144', '12240.00'],
 ['3', '2020100403012011', 'NRIC', '42', '42', '40', '895', '35800.00'],
 ['4', '2020100403012800', 'GLICL', '38', '33', '488', '635', '309880.00'],
 ['5', '2020100403011977', 'NRIC', '42', '35', '50', '895', '44750.00'],
 ['6', '2020100401028129', 'AIL', '42', '26', '10', '520', '5200.00'],
 ['7', '2020100401027400', 'PRIN', '34', '49', '50', '615', '30750.00'],
 ['8', '2020100401028135', 'AIL', '34', '45', '10', '520', '5200.00'],
 ['9', '2020100401029756', 'NICL', '35', '42', '59', '571', '33689.00'],
 ['10', '2020100403012797', 'GLICL', '38', '33', '200', '635', '127000.00'],
 ['11', '2020100401028150', 'AIL', '57', '45', '20', '518', '10360.00'],
 ['12', '2020100403011937', 'NRIC', '42', '32', '400', '891', '356400.00'],
 ['13', '2020100403012016', 'NRIC', '42', '39', '40', '895', '35800.00'],
 ['14', '2020100403012382', 'NLBBL', '57', '28', '14', '761', '10654.00'],
 ['15', '2020100401029897', 'NICL', '57', '14', '102', '570', '58140.00'],
 ['16', '2020100401027398', 'BOKL', '38', '28', '300', '280', '84000.00'],
 ['17', '2020100401029708', 'AKPL', '19', '44', '95', '235', '22325.00'],
 ['18', '2020100403011987', 'NRIC', '42', '33', '40', '895', '35800.00'],
 ['19', '2020100403012015', 'NRIC', '42', '1', '40', '895', '35800.00'],
 ['20', '2020100401029805', 'SJCL', '18', '40', '20', '171', '3420.00']]

In [17]:
import csv
n = len(list2)
with open('nepal.csv','a') as csvFile:
  writer = csv.writer(csvFile)
  for i in range(n):
    writer.writerow(list2[i])

In [18]:
import pandas as pd
df = pd.read_csv('nepal.csv')
df

,S.N.,Contract No,Stock Symbol,Buyer Broker,Seller Broker,Quantity,Rate,Amount
0,1,2020100403012017,NRIC,42,56,40,895,35800.0
1,2,2020100403012814,GUFL,38,5,85,144,12240.0
2,3,2020100403012011,NRIC,42,42,40,895,35800.0
3,4,2020100403012800,GLICL,38,33,488,635,309880.0
4,5,2020100403011977,NRIC,42,35,50,895,44750.0
5,6,2020100401028129,AIL,42,26,10,520,5200.0
6,7,2020100401027400,PRIN,34,49,50,615,30750.0
7,8,2020100401028135,AIL,34,45,10,520,5200.0
8,9,2020100401029756,NICL,35,42,59,571,33689.0
9,10,2020100403012797,GLICL,38,33,200,635,127000.0
10,11,2020100401028150,AIL,57,45,20,518,10360.0
11,12,2020100403011937,NRIC,42,32,400,891,356400.0
12,13,2020100403012016,NRIC,42,39,40,895,35800.0
13,14,2020100403012382,NLBBL,57,28,14,761,10654.0
14,15,2020100401029897,NICL,57,14,102,570,58140.0
15,16,2020100401027398,BOKL,38,28,300,280,84000.0
16,17,2020100401029708,AKPL,19,44,95,235,22325.0
17,18,2020100403011987,NRIC,42,33,40,895,35800.0
18,19,2020100403012015,NRIC,42,1,40,895,35800.0
19,20,2020100401029805,SJCL,18,40,20,171,3420.0

In [1]:
print("hello")

hello

In [25]:
#for multiple
from bs4 import BeautifulSoup
import requests
n=int(input("how many page you want?"))
final=[]
for i in range(1,n+1):
    url=BeautifulSoup(f"http://www.nepalstock.com/main/floorsheet/index/{i}/","html.parser")
    response=requests.get(url)
    data=response.text
    soup=BeautifulSoup(data,'lxml')
    #soup
    tag=soup.table
    tags=tag.find_all('tr')
    #tags
    list1=[]
    for i in range(len(tags)):
        x=tags[i].get_text()
        list1.append(x)
    #list1
    list1=list1[1:-3]
    list2=[]
    for i in list1:
        y=i.split('\n')[1:-1]
        list2.append(y)
    final=final+list2
final

how many page you want?8

[['S.N.',
  'Contract No',
  'Stock Symbol',
  'Buyer Broker',
  'Seller Broker',
  'Quantity',
  'Rate',
  'Amount'],
 ['1', '2020100403012017', 'NRIC', '42', '56', '40', '895', '35800.00'],
 ['2', '2020100403012814', 'GUFL', '38', '5', '85', '144', '12240.00'],
 ['3', '2020100403012011', 'NRIC', '42', '42', '40', '895', '35800.00'],
 ['4', '2020100403012800', 'GLICL', '38', '33', '488', '635', '309880.00'],
 ['5', '2020100403011977', 'NRIC', '42', '35', '50', '895', '44750.00'],
 ['6', '2020100401028129', 'AIL', '42', '26', '10', '520', '5200.00'],
 ['7', '2020100401027400', 'PRIN', '34', '49', '50', '615', '30750.00'],
 ['8', '2020100401028135', 'AIL', '34', '45', '10', '520', '5200.00'],
 ['9', '2020100401029756', 'NICL', '35', '42', '59', '571', '33689.00'],
 ['10', '2020100403012797', 'GLICL', '38', '33', '200', '635', '127000.00'],
 ['11', '2020100401028150', 'AIL', '57', '45', '20', '518', '10360.00'],
 ['12', '2020100403011937', 'NRIC', '42', '32', '400', '891', '356400.00'],
 ['13', '2020100403012016', 'NRIC', '42', '39', '40', '895', '35800.00'],
 ['14', '2020100403012382', 'NLBBL', '57', '28', '14', '761', '10654.00'],
 ['15', '2020100401029897', 'NICL', '57', '14', '102', '570', '58140.00'],
 ['16', '2020100401027398', 'BOKL', '38', '28', '300', '280', '84000.00'],
 ['17', '2020100401029708', 'AKPL', '19', '44', '95', '235', '22325.00'],
 ['18', '2020100403011987', 'NRIC', '42', '33', '40', '895', '35800.00'],
 ['19', '2020100403012015', 'NRIC', '42', '1', '40', '895', '35800.00'],
 ['20', '2020100401029805', 'SJCL', '18', '40', '20', '171', '3420.00'],
 ['S.N.',
  'Contract No',
  'Stock Symbol',
  'Buyer Broker',
  'Seller Broker',
  'Quantity',
  'Rate',
  'Amount'],
 ['21', '2020100401028322', 'RADHI', '57', '18', '11', '253', '2783.00'],
 ['22', '2020100403011925', 'PLIC', '20', '38', '50', '671', '33550.00'],
 ['23', '2020100403011966', 'NRIC', '42', '48', '100', '894', '89400.00'],
 ['24', '2020100403011994', 'NRIC', '42', '8', '40', '895', '35800.00'],
 ['25', '2020100401027319', 'PRVU', '58', '6', '100', '249', '24900.00'],
 ['26', '2020100404003324', 'RLI', '34', '28', '10', '624', '6240.00'],
 ['27', '2020100401027294', 'CBL', '7', '1', '1000', '163', '163000.00'],
 ['28', '2020100401028300', 'UNHPL', '48', '45', '400', '110', '44000.00'],
 ['29', '2020100401029878', 'NBL', '58', '28', '100', '332', '33200.00'],
 ['30', '2020100403013176', 'KSBBL', '34', '16', '571', '201', '114771.00'],
 ['31', '2020100401029807', 'HDL', '58', '54', '95', '1905', '180975.00'],
 ['32', '2020100401027318', 'PRVU', '58', '6', '17', '248', '4216.00'],
 ['33', '2020100401027420', 'UMHL', '48', '38', '10', '146', '1460.00'],
 ['34', '2020100401028894', 'PRVU', '48', '25', '500', '249', '124500.00'],
 ['35', '2020100403012435', 'NRIC', '48', '29', '40', '893', '35720.00'],
 ['36', '2020100401027311', 'PRVU', '58', '45', '369', '248', '91512.00'],
 ['37', '2020100401028178', 'NBL', '58', '42', '5000', '332', '1660000.00'],
 ['38', '2020100404003439', 'NIBPO', '48', '13', '500', '368', '184000.00'],
 ['39', '2020100401029741', 'NIL', '7', '57', '29', '840', '24360.00'],
 ['40', '2020100401028211', 'NHPC', '8', '58', '1000', '97', '97000.00'],
 ['S.N.',
  'Contract No',
  'Stock Symbol',
  'Buyer Broker',
  'Seller Broker',
  'Quantity',
  'Rate',
  'Amount'],
 ['41', '2020100401028297', 'LEC', '55', '20', '40', '201', '8040.00'],
 ['42', '2020100401027440', 'NCCB', '55', '6', '1950', '228', '444600.00'],
 ['43', '2020100401028278', 'LEC', '55', '21', '20', '201', '4020.00'],
 ['44', '2020100403012766', 'SWBBL', '47', '59', '75', '1268', '95100.00'],
 ['45', '2020100403012819', 'CFCL', '26', '17', '50', '156', '7800.00'],
 ['46', '2020100403012397', 'NRN', '26', '22', '10', '362', '3620.00'],
 ['47', '2020100401028284', 'NICL', '17', '42', '15', '572', '8580.00'],
 ['48', '2020100401029894', 'NICL', '32', '14', '300', '570', '171000.00'],
 ['49', '2020100403012428', 'LBBL', '32', '59', '100', '209', '20900.00'],
 ['50', '2020100401028998', 'BOKL', '17', '40', '100', '280', '28000.00'],
 ['51', '2020100401029077', 'NCCB', '32', '4', '10', '228', '2280.00'],
 ['52', '2020100403012804', 'GBLBS', '53', '48', '50', '521', '26050.00'],
 ['53', '2020100403012813', 'PFL', '53', '39', '36', '173', '6228.00'],
 ['54', '2020100401029729', 'CZBIL', '50', '14', '1196', '216', '258336.00'],
 ['55', '2020100401029040', 'NHPC', '42', '59', '200', '96', '19200.00'],
 ['56', '2020100401027306', 'CBL', '42', '1', '70', '162', '11340.00'],
 ['57', '2020100401028993', 'NHPC', '5', '41', '180', '96', '17280.00'],
 ['58', '2020100401028324', 'PMHPL', '22', '4', '10', '134', '1340.00'],
 ['59', '2020100401029861', 'CZBIL', '50', '51', '50', '216', '10800.00'],
 ['60', '2020100401028289', 'NBB', '5', '56', '12', '226', '2712.00'],
 ['S.N.',
  'Contract No',
  'Stock Symbol',
  'Buyer Broker',
  'Seller Broker',
  'Quantity',
  'Rate',
  'Amount'],
 ['61', '2020100403012824', 'UFL', '42', '45', '189', '248', '46872.00'],
 ['62', '2020100403012817', 'JBBL', '5', '58', '100', '193', '19300.00'],
 ['63', '2020100401029813', 'NMB', '4', '42', '10', '418', '4180.00'],
 ['64', '2020100401028288', 'NBB', '5', '41', '500', '225', '112500.00'],
 ['65', '2020100401028287', 'NBB', '5', '49', '100', '225', '22500.00'],
 ['66', '2020100401029084', 'PPCL', '43', '26', '10', '163', '1630.00'],
 ['67', '2020100401029914', 'UPPER', '25', '57', '50', '277', '13850.00'],
 ['68', '2020100403012451', 'GBBL', '14', '42', '213', '254', '54102.00'],
 ['69', '2020100403013206', 'CIT', '43', '44', '10', '3500', '35000.00'],
 ['70', '2020100401027443', 'PMHPL', '14', '58', '10', '133', '1330.00'],
 ['71', '2020100401028197', 'NBL', '25', '42', '196', '331', '64876.00'],
 ['72', '2020100404003332', 'RLI', '25', '28', '10', '624', '6240.00'],
 ['73', '2020100401028175', 'NBL', '14', '42', '500', '332', '166000.00'],
 ['74', '2020100403012400', 'GLBSL', '52', '21', '10', '726', '7260.00'],
 ['75', '2020100401028202', 'BOKL', '52', '41', '20', '281', '5620.00'],
 ['76', '2020100401029866', 'NIB', '25', '35', '18', '420', '7560.00'],
 ['77', '2020100401028988', 'BPCL', '25', '45', '152', '401', '60952.00'],
 ['78', '2020100403012440', 'GBBL', '25', '42', '486', '255', '123930.00'],
 ['79', '2020100403012832', 'PFL', '34', '32', '15', '176', '2640.00'],
 ['80', '2020100401029067', 'NMB', '48', '42', '450', '418', '188100.00'],
 ['S.N.',
  'Contract No',
  'Stock Symbol',
  'Buyer Broker',
  'Seller Broker',
  'Quantity',
  'Rate',
  'Amount'],
 ['81', '2020100401029754', 'SHIVM', '7', '4', '100', '824', '82400.00'],
 ['82', '2020100403013196', 'KSBBL', '48', '38', '10', '200', '2000.00'],
 ['83', '2020100403013145', 'NRIC', '6', '16', '10', '891', '8910.00'],
 ['84', '2020100401027381', 'NBL', '58', '11', '90', '332', '29880.00'],
 ['85', '2020100403012436', 'NRIC', '48', '6', '40', '893', '35720.00'],
 ['86', '2020100401029806', 'UPCL', '6', '49', '50', '122', '6100.00'],
 ['87', '2020100403011918', 'SLICL', '48', '56', '30', '624', '18720.00'],
 ['88', '2020100401028196', 'NBL', '6', '42', '500', '331', '165500.00'],
 ['89', '2020100401028892', 'PRVU', '48', '38', '920', '249', '229080.00'],
 ['90', '2020100403011899', 'NRN', '6', '20', '10', '362', '3620.00'],
 ['91', '2020100401028936', 'HGI', '41', '52', '1000', '523', '523000.00'],
 ['92', '2020100401027305', 'CBL', '16', '1', '500', '162', '81000.00'],
 ['93', '2020100401027293', 'CBL', '28', '1', '100', '163', '16300.00'],
 ['94', '2020100401028249', 'EBL', '29', '47', '50', '728', '36400.00'],
 ['95', '2020100401028957', 'UPPER', '16', '21', '50', '274', '13700.00'],
 ['96', '2020100401029021', 'AKJCL', '38', '26', '20', '115', '2300.00'],
 ['97', '2020100401029815', 'GBIME', '45', '48', '400', '279', '111600.00'],
 ['98', '2020100401027343', 'LBL', '33', '8', '500', '266', '133000.00'],
 ['99', '2020100401029053', 'BPCL', '1', '34', '300', '401', '120300.00'],
 ['100', '2020100403011883', 'PROFL', '45', '45', '500', '139', '69500.00'],
 ['S.N.',
  'Contract No',
  'Stock Symbol',
  'Buyer Broker',
  'Seller Broker',
  'Quantity',
  'Rate',
  'Amount'],
 ['101', '2020100403011890', 'JFL', '45', '49', '300', '202', '60600.00'],
 ['102', '2020100401028262', 'MBL', '45', '49', '54', '249', '13446.00'],
 ['103', '2020100403012381', 'NMBMF', '45', '33', '200', '818', '163600.00'],
 ['104', '2020100401028225', 'PRVU', '45', '4', '100', '247', '24700.00'],
 ['105', '2020100401029050', 'NIB', '1', '41', '111', '419', '46509.00'],
 ['106', '2020100403011884', 'PROFL', '45', '45', '1000', '139', '139000.00'],
 ['107', '2020100401027281', 'NIL', '50', '58', '200', '840', '168000.00'],
 ['108', '2020100401028280', 'UPPER', '45', '58', '18', '275', '4950.00'],
 ['109', '2020100401028232', 'MBL', '45', '34', '150', '250', '37500.00'],
 ['110', '2020100401028239', 'LBL', '33', '19', '200', '267', '53400.00'],
 ['111', '2020100403011891', 'NRIC', '6', '42', '10', '890', '8900.00'],
 ['112', '2020100403013203', 'KSBBL', '36', '38', '100', '200', '20000.00'],
 ['113', '2020100401027406', 'SCB', '6', '45', '74', '668', '49432.00'],
 ['114', '2020100401028209', 'BOKL', '44', '41', '300', '281', '84300.00'],
 ['115', '2020100401028163', 'GBIME', '37', '48', '44', '279', '12276.00'],
 ['116', '2020100403012452', 'GBBL', '37', '42', '100', '254', '25400.00'],
 ['117', '2020100401029925', 'GHL', '44', '43', '30', '116', '3480.00'],
 ['118', '2020100401027409', 'SCB', '6', '59', '28', '668', '18704.00'],
 ['119', '2020100401027309', 'MBL', '44', '33', '128', '248', '31744.00'],
 ['120', '2020100401027288', 'AIL', '6', '47', '10', '520', '5200.00'],
 ['S.N.',
  'Contract No',
  'Stock Symbol',
  'Buyer Broker',
  'Seller Broker',
  'Quantity',
  'Rate',
  'Amount'],
 ['121', '2020100401029924', 'GHL', '44', '59', '90', '115', '10350.00'],
 ['122', '2020100401027334', 'SIL', '44', '3', '84', '770', '64680.00'],
 ['123', '2020100401029000', 'BOKL', '28', '17', '50', '281', '14050.00'],
 ['124', '2020100403012389', 'PLIC', '16', '49', '443', '671', '297253.00'],
 ['125', '2020100401027358', 'API', '16', '57', '500', '188', '94000.00'],
 ['126', '2020100401028992', 'NHPC', '38', '41', '220', '96', '21120.00'],
 ['127', '2020100401029074', 'MEGA', '38', '58', '450', '231', '103950.00'],
 ['128', '2020100403013142', 'GBLBS', '28', '48', '50', '525', '26250.00'],
 ['129', '2020100403012393', 'SLBSL', '38', '14', '13', '809', '10517.00'],
 ['130', '2020100403012448', 'GBBL', '28', '42', '60', '255', '15300.00'],
 ['131', '2020100403012861', 'SDLBSL', '16', '28', '10', '823', '8230.00'],
 ['132', '2020100401028977', 'UMHL', '16', '29', '250', '145', '36250.00'],
 ['133', '2020100403013163', 'KSBBL', '29', '43', '1424', '200', '284800.00'],
 ['134', '2020100401029044', 'NHPC', '58', '59', '335', '96', '32160.00'],
 ['135', '2020100403012866', 'SPARS', '38', '38', '1', '960', '960.00'],
 ['136', '2020100403012447', 'GBBL', '29', '42', '500', '255', '127500.00'],
 ['137', '2020100404003226', 'LUK', '26', '6', '300', '8.77', '2631.00'],
 ['138', '2020100401027330', 'NMB', '55', '1', '27', '417', '11259.00'],
 ['139', '2020100401028290', 'LEC', '55', '22', '10', '201', '2010.00'],
 ['140', '2020100401027445', 'NBL', '8', '59', '227', '332', '75364.00'],
 ['S.N.',
  'Contract No',
  'Stock Symbol',
  'Buyer Broker',
  'Seller Broker',
  'Quantity',
  'Rate',
  'Amount'],
 ['141', '2020100403011886', 'PROFL', '10', '45', '500', '139', '69500.00'],
 ['142', '2020100403012843', 'SKBBL', '47', '19', '25', '1386', '34650.00'],
 ['143', '2020100403013204', 'MNBBL', '46', '33', '200', '334', '66800.00'],
 ['144', '2020100401027368', 'LEC', '55', '58', '10', '201', '2010.00'],
 ['145', '2020100403013187', 'JBBL', '55', '58', '500', '193', '96500.00'],
 ['146', '2020100403013139', 'JBBL', '55', '34', '500', '194', '97000.00'],
 ['147', '2020100404003326', 'LUK', '47', '49', '1000', '8.76', '8760.00'],
 ['148', '2020100401028222', 'GHL', '26', '43', '20', '115', '2300.00'],
 ['149', '2020100401028991', 'NBL', '26', '45', '301', '332', '99932.00'],
 ['150', '2020100401027302', 'CBL', '46', '1', '200', '162', '32400.00'],
 ['151', '2020100401029752', 'GBIME', '10', '48', '1000', '279', '279000.00'],
 ['152', '2020100403012751', 'GILB', '44', '59', '40', '1200', '48000.00'],
 ['153', '2020100401028199', 'NBL', '3', '44', '287', '333', '95571.00'],
 ['154', '2020100401028888', 'AKPL', '1', '45', '100', '235', '23500.00'],
 ['155', '2020100403011907', 'SLBBL', '45', '58', '20', '856', '17120.00'],
 ['156', '2020100401029870', 'ADBL', '1', '34', '62', '442', '27404.00'],
 ['157', '2020100403013183', 'NRN', '35', '45', '10', '361', '3610.00'],
 ['158', '2020100403013155', 'LBBL', '44', '1', '200', '208', '41600.00'],
 ['159', '2020100401027364', 'KPCL', '44', '47', '10', '158', '1580.00'],
 ['160', '2020100401028255', 'SBL', '1', '34', '100', '323', '32300.00']]

In [26]:
import csv
n = len(final)
with open('final.csv','a') as csvFile:
  writer = csv.writer(csvFile)
  for i in range(n):
    writer.writerow(final[i])

In [27]:
import pandas as pd
df = pd.read_csv('final.csv')
df

,S.N.,Contract No,Stock Symbol,Buyer Broker,Seller Broker,Quantity,Rate,Amount
0,1,2020100403012017,NRIC,42,56,40,895,35800.00
1,2,2020100403012814,GUFL,38,5,85,144,12240.00
2,3,2020100403012011,NRIC,42,42,40,895,35800.00
3,4,2020100403012800,GLICL,38,33,488,635,309880.00
4,5,2020100403011977,NRIC,42,35,50,895,44750.00
...,...,...,...,...,...,...,...,...
204,156,2020100401029870,ADBL,1,34,62,442,27404.00
205,157,2020100403013183,NRN,35,45,10,361,3610.00
206,158,2020100403013155,LBBL,44,1,200,208,41600.00
207,159,2020100401027364,KPCL,44,47,10,158,1580.00
208,160,2020100401028255,SBL,1,34,100,323,32300.00

In [21]:
print("hello")

hello

In [8]:
print("sfg")

sfg